### ISSUE TITLE
Standalone release deson't work

### ISSUE THREAD

**Issue by heiwiper** [HicServices/BadMedicine.Dicom#68]
I tried different versions on both Linux and Windows but I would either get the error mentioned in #59  or this :
```
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/abdallah/Downloads/linux-x64/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```
Note : this output is from Linux but I had almost the same output on Windows with different library file format.
Can you please fix this issue or point me to the right direction if I am missing out on something ? I really need this app and can't find something similar elsewhere (if you happen to know a similar program let me know)

**Comment by tznind** [comment]
Hey, thanks for reporting this.  I will try to investigate next week and fix the Releases.

I know it is less than ideal but you should be able to build the source yourself if you have the dotnet sdk (dotnet core 3.1 sdk) :

![image](https://user-images.githubusercontent.com/31306100/141321789-63c5a321-8507-4dea-96f8-d0cb8177cd89.png)


Use
```
dotnet build
cd BadMedicine.Dicom-master\BadDicom\bin\Debug\netcoreapp3.1
.\BadDicom.exe --help
```

**Comment by HeiWiper** [comment]
I tried to follow your instructions and compiled the code on Linux and Windows. The process went fine on Windows however I have had a some troubles compiling on Linux. First, I got the same error as the one mentioned in my previous post in this issue. I realized I had to set the a dotnet variable so that the program can find dotnet runtime. Tried to execute the app again and got this error :
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser+<>c.<.cctor>b__20_0()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(System.Threading.LazyThreadSafetyMode)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(System.LazyHelper, Boolean)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at CommandLine.Parser.get_Default()
   at BadDicom.Program.Main(System.String[])
Aborted
```
I found a fix on [stackoverflow](https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in) which seems to solve that issue and I could run the `--help` command but when I tried to generate images I got the following error :
```
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateSolidFill(Int32 color, IntPtr& brush)
   at System.Drawing.SolidBrush..ctor(Color color)
   at BadMedicine.Dicom.PixelDrawer..ctor() in /home/abdallah/Downloads/BadMedicine.Dicom-master/BadMedicine.Dicom/PixelDrawer.cs:line 16
   at BadMedicine.Dicom.DicomDataGenerator..ctor(Random r, DirectoryInfo outputDir, String[] modalities) in /home/abdallah/Downloads/BadMedicine.Dicom-master/BadMedicine.Dicom/DicomDataGenerator.cs:line 53
   at BadDicom.Program.GetDataGenerator(ProgramOptions opts, IPersonCollection identifiers, Random r, DirectoryInfo& dir) in /home/abdallah/Downloads/BadMedicine.Dicom-master/BadDicom/Program.cs:line 120
   at BadDicom.Program.RunOptionsAndReturnExitCode(ProgramOptions opts) in /home/abdallah/Downloads/BadMedicine.Dicom-master/BadDicom/Program.cs:line 94
```

**Comment by jas88** [comment]
Yes, on Linux you need both the "libgdiplus" and "libicu" packages installed to avoid these errors. There's a slightly different workaround needed for MacOS, too; we should probably incorporate/document this next release.

**Comment by HeiWiper** [comment]
> Yes, on Linux you need both the "libgdiplus" and "libicu" packages installed to avoid these errors. There's a slightly different workaround needed for MacOS, too; we should probably incorporate/document this next release.

I do have the `libicu` package installed and still had that first error, installing `libgdiplus` didn't fix the second error either :(

**Comment by tznind** [comment]
Hmn it might be how you are building it.  I think `publish` is more reliable on linux.  Can you try the following please (and provide the output):

```bash
dotnet --list-sdks

dotnet publish -r linux-x64

cd bin/Debug/netcoreapp3.1/linux-x64/publish

./BadDicom --help

./BadDicom -s -1 ./dicoms 500 10 CT
```
I have tested this on my ubuntu  20.04 laptop and didn't have to install any additional libraries (although it's possible that some of those packages might already be installed).

**Comment by HeiWiper** [comment]
```
:~/Downloads/BadMedicine.Dicom-master/BadDicom$ dotnet --list-sdks

3.1.415 [/snap/dotnet-sdk/148/sdk]
```
```
:~/Downloads/BadMedicine.Dicom-master/BadDicom$ dotnet publish -r linux-x64

Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/abdallah/Downloads/BadMedicine.Dicom-master/BadMedicine.Dicom/BadMedicine.Dicom.csproj (in 17.91 sec).
  Restored /home/abdallah/Downloads/BadMedicine.Dicom-master/BadDicom/BadDicom.csproj (in 3.34 min).
/home/abdallah/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory '/home/abdallah/Downloads/BadMedicine.Dicom-master/BadMedicine.Dicom'. [/home/abdallah/Downloads/BadMedicine.Dicom-master/BadMedicine.Dicom/BadMedicine.Dicom.csproj]
/home/abdallah/.nuget/packages/microsoft.sourcelink.common/1.0.0/build/Microsoft.SourceLink.Common.targets(52,5): warning : Source control information is not available - the generated source link is empty. [/home/abdallah/Downloads/BadMedicine.Dicom-master/BadMedicine.Dicom/BadMedicine.Dicom.csproj]
  BadMedicine.Dicom -> /home/abdallah/Downloads/BadMedicine.Dicom-master/BadMedicine.Dicom/bin/Debug/netstandard2.0/BadMedicine.Dicom.dll
/home/abdallah/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory '/home/abdallah/Downloads/BadMedicine.Dicom-master/BadDicom'. [/home/abdallah/Downloads/BadMedicine.Dicom-master/BadDicom/BadDicom.csproj]
/home/abdallah/.nuget/packages/microsoft.sourcelink.common/1.0.0/build/Microsoft.SourceLink.Common.targets(52,5): warning : Source control information is not available - the generated source link is empty. [/home/abdallah/Downloads/BadMedicine.Dicom-master/BadDicom/BadDicom.csproj]
  BadDicom -> /home/abdallah/Downloads/BadMedicine.Dicom-master/BadDicom/bin/Debug/netcoreapp3.1/linux-x64/BadDicom.dll
  BadDicom -> /home/abdallah/Downloads/BadMedicine.Dicom-master/BadDicom/bin/Debug/netcoreapp3.1/linux-x64/publish/
```
```
:~/Downloads/BadMedicine.Dicom-master/BadDicom/bin/Debug/netcoreapp3.1/linux-x64/publish$ ./BadDicom --help

Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser+<>c.<.cctor>b__20_0()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(System.Threading.LazyThreadSafetyMode)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(System.LazyHelper, Boolean)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at CommandLine.Parser.get_Default()
   at BadDicom.Program.Main(System.String[])
Aborted
```

Last command has the same output as the previous one.

**Comment by rkm** [comment]
this looks to be an issue with the snap installation of dotnet: https://askubuntu.com/questions/1330986/running-dotnet-run-command-throws-error-couldnt-find-a-valid-icu-package-instal.

You can try setting the following environment variable:

```console
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

**Comment by tznind** [comment]
Good catch @rkm .  I know there are a few issues with snap installs of dotnet sdk.  @jas88 is updating the repo to use dotnet5 (currently this repo uses 3.1) on PR https://github.com/HicServices/BadMedicine.Dicom/pull/61.  That should hopefully fix the problem with the release binaries.  

@HeiWiper  are you able to run other dotnet applications ok? e.g. 

```
dotnet new console
dotnet run
```

**Comment by HeiWiper** [comment]
> this looks to be an issue with the snap installation of dotnet: https://askubuntu.com/questions/1330986/running-dotnet-run-command-throws-error-couldnt-find-a-valid-icu-package-instal.
> 
> You can try setting the following environment variable:
> 
> ```
> export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
> ```

I mentioned that workaround in a previous comment, it solves the missing ICU package issue but when trying to generate images I would get the Gdip missing issue. However, I tried to install dotnet from the package manager and used the `dotnet build` and it worked just fine, so it must have to do with snap packages as you said. I wonder if it's only an issue with the 3.1 dotnet snap package.




> @HeiWiper are you able to run other dotnet applications ok? e.g.
> 
> ```
> mkdir test
> cd ./test
> dotnet new console
> dotnet run
> ```

Here's the output of the third command:
```
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/abdallah/test/test.csproj...
  Determining projects to restore...
  Restored /home/abdallah/test/test.csproj (in 132 ms).

Restore succeeded.
```
The last command had no output.

**Comment by tznind** [comment]
> However, I tried to install dotnet from the package manager and used the `dotnet build` and it worked just fine, so it must have to do with snap packages as you said. I wonder if it's only an issue with the 3.1 dotnet snap package.

Thats great that you were able to get it working and generate test images! 

I will leave this ticket open as I think there is still an outstanding issue that the `Releases` are not working out of the box and I don't think that is the same issue as you were having with snap and dotnet build.  Hopefully it will be easy to fix though especially with @jas88 PR and update to dotnet5.  There is probably just something a bit off about the CI script.

> The last command had no output.

I was expecting it to say something like Hello World in the console but I guess it depends on exactly what the `Console Application` template is defined as in the sdk.  I think dotnet5 has a call to Console.WriteLine but maybe 3.1 doesn't.  But no worries I mostly got you to run that to make sure that the dotnet command was behaving for a regular project and it seems you've managed to fix that now by installing from the package manager.

**Comment by HeiWiper** [comment]
Thank you so much this was very helpful, also I tried the release package after fixing the `dotnet` installation but to no avail. The build version is enough for me right now, I just thought it would take time to build the package that's why I directly tried to run the release packages in the beginning.
Let me know if I can help with by testing the release packages if that would be helpful to you in some way.

**Comment by tznind** [comment]
Version 0.0.10 (https://github.com/HicServices/BadMedicine.Dicom/releases/tag/v0.0.10) should be fixed.  Sorry it took so long.

**Comment by heiwiper** [comment]
> Version 0.0.10 (https://github.com/HicServices/BadMedicine.Dicom/releases/tag/v0.0.10) should be fixed. Sorry it took so long.

Thank you so much! I can confirm it works out of the box.
I wanted to ask if I can port this app to C++ but I didn't want to open an issue and couldn't find your email to contact you. I didn't check the code yet but I checked the `LICENSE` and `README` which mentioned Scottish medical imaging data. So I wasn't sure if this data is freely available or not.

**Comment by jas88** [comment]
Rewriting it in C++ would be a big undertaking! The Scottish Medical Imaging project is developing software for handling large volumes of medical imaging data; the code is all freely available here on Github, all under either HicServices or SMI, but the data is very much restricted, which was one of the reasons for developing tools like this: we can develop and test the code against synthetic "dummy" images and patient data without any restrictions.
