### ISSUE TITLE
Use of System.Drawing.Common makes library Windows-only

### ISSUE THREAD

**Issue by jas88** [HicServices/BadMedicine.Dicom#81]
**Describe the bug**

Using the legacy System.Drawing.Common library introduces a hidden Windows dependency, for which the libgdiplus Linux shim partially compensates. With the new fo-dicom 5.0 flexibility, we should be using the platform-neutral ImageSharp tooling instead

Exposed by Dependabot opening a PR to System.Drawing.Common 6.0.0, which explicitly fails builds which rely on Windows components on non-Windows platforms.

**Comment by tznind** [comment]
What do we actually use `System.Drawing.Common` for? I removed it from RDMP in https://github.com/HicServices/RDMP/pull/667 and from SmiServices in https://github.com/SMI/SmiServices/pull/968 so presumably we can do the same thing in BadMedicine.Dicom.

I don't think we actually use anything that is specific to the `Common` namespace/dependency.  So no need to switch to ImageSharp etc just axe the dependency I think.

**Comment by jas88** [comment]
DicomTemplateBuilder used it to copy the pixel data onto a Bitmap for the GUI, which took about 4 lines to replace; BadMedicine.Dicom uses it to write some text on an image for the dummy pixel data. Should be pretty trivial to replace too.
